### PR TITLE
Nn precision fix (#124)

### LINKED ISSUE #124: natural_neighbor interpolation sometimes returns NAN
`natural_neighbor` interpolation sometimes returns `NAN`. It looks randomly but if I run it twice with the same input then `None`s are returned at the same positions.

Tried also with `barycentric` and that works without this defect.

Sample: [out-nni.tif.gz](https://github.com/user-attachments/files/18803582/out-nni.tif.gz)

### PR DESCRIPTION
**Pull request by Stoeoef**
Fixes #124

### CODE REVIEW

File: src/delaunay_core/interpolation.rs [hunk 1]
```diff
@@ -524,7 +531,16 @@ where
...
-                let current = last_edge.face().as_inner().unwrap().circumcenter();
+                let vertices = last_edge
+                    .face()
+                    .as_inner()
+                    .unwrap()
+                    .positions()
+                    .map(|p| p.sub(position));
+
+                let current = math::circumcenter(vertices).0;
+                last_edge.face();
```
Comment (zdila) [inline src/delaunay_core/interpolation.rs:542]: just for sure, does this line have any effect?

Comment (Stoeoef) [reply src/delaunay_core/interpolation.rs]: Whoops! Thanks, that was a leftover from some debugging. Removed.
